import {
  StyleSheet
} from 'react-native';
import {StyleConfig} from './index';
const oPx = StyleConfig.oPx;

export const styles = StyleSheet.create({
	scrollView:{
    paddingBottom:100/oPx,
		backgroundColor:'#f5f5f5'
	},
	swiper:{
    height:375/oPx
	},
	img:{
    width:750/oPx,
    height:375/oPx
	},
  //类别
  kind:{
    alignItems:'center',
    width:750/oPx,
    height:195/oPx,
    flexDirection:'row',
    backgroundColor:'#e5e5e5',
    borderWidth:1,
    borderColor:'#dcdcdc',
    justifyContent:'center',
  },
  kind_one:{
    flex:1,
    justifyContent:'center',
    alignItems:'center',
  },
  kind_img:{
    width:94/oPx,
    height:94/oPx
  },
  kind_text:{
    fontSize:28/oPx,
    color:'#666',
    paddingTop:12/oPx,
    fontWeight:'200'
  },
  //底部
  footLine:{
    marginTop:20/oPx,
    marginBottom:20/oPx,
    flexDirection:'row',
    justifyContent:'center'
  },
  footerTitle:{
    fontSize:24/oPx,
    color:'#666',
    fontWeight:'200'
  },
  footerImg:{
    width:25/oPx,
    height:30/oPx,
    marginRight:10/oPx
  },
  user:{
    fontSize:24/oPx,
    color:'#999',
    textAlign:'center',
    /*width:750/oPx,*/
    marginBottom:20/oPx,
  },
  money:{
    color:'#f57b25',
    textAlign:'center',
  },
  scroll:{
    height:24/oPx,
    marginBottom:20/oPx,
    //width:750/oPx,
    justifyContent:'center'
  },
  listView:{
    backgroundColor:'#e9ecf3',
    marginTop:16/oPx
  },
  moreBottom:{
    height:80/oPx,
    justifyContent:'center',
    alignItems:'center'
  }
})
